#!/bin/bash

# Define the variable to hold the .env file path
env_file='./client/.env'

# Check if GITPOD_WORKSPACE_URL is in ./client/.env
if grep -qF 'NEXT_PUBLIC_GITPOD_WORKSPACE_URL' "$env_file"; then
    # If it exists, update its value
    sed -i "s|^NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\".*\"$|NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\"${GITPOD_WORKSPACE_URL}\"|" "$env_file"
else
    # If not present, append the line
    echo "
NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\"${GITPOD_WORKSPACE_URL}\"" >> "$env_file"
fi

unlink ./server/.env
cp $env_file ./server/.env

docker compose down --volumes
docker compose up client server --build --remove-orphans --force-recreate