#!/bin/bash

# Path to the client .env
env_file='./client/.env'

# Check if NEXT_PUBLIC_GITPOD_WORKSPACE_URL is in ./client/.env
if grep -qF 'NEXT_PUBLIC_GITPOD_WORKSPACE_URL' "$env_file"; then
    # If it exists, update its value
    sed -i "s|^NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\".*\"$|NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\"${GITPOD_WORKSPACE_URL}\"|" "$env_file"
else
    # If not present, append the line
    echo "
NEXT_PUBLIC_GITPOD_WORKSPACE_URL=\"${GITPOD_WORKSPACE_URL}\"" >> "$env_file"
fi

# Delete the .env file in ./server if it exits and copy the .env file from ./client
unlink ./server/.env
cp $env_file ./server/.env

# Install correct node version and install dependencies
nvm install
nvm use
npm run install-dependencies

# Start the application
docker compose down --volumes
docker compose up client server --build --remove-orphans --force-recreate