FROM node:21.0.0

WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm@9.1.1

# Rest of your Dockerfile instructions
COPY package*.json ./

RUN pnpm install --production  # Consider using --production for prod builds

COPY . .

RUN pnpm run serverbuild

EXPOSE 3005

CMD ["pnpm", "start"]
